import { property, Sheet, Value } from '../..';
import { Keyword } from '../../constants';

export namespace Cursor {
    export const set = (...values: Value[]): Sheet => ({cursor: property(values)});
    export const AUTO: Sheet = set(Keyword.AUTO);
    export const DEFAULT: Sheet = set(Keyword.DEFAULT);
    export const NONE: Sheet = set(Keyword.NONE);
    export const CONTEXT_MENU: Sheet = set(Keyword.CONTEXT_MENU);
    export const HELP: Sheet = set(Keyword.HELP);
    export const POINTER: Sheet = set(Keyword.POINTER);
    export const PROGRESS: Sheet = set(Keyword.PROGRESS);
    export const WAIT: Sheet = set(Keyword.WAIT);
    export const CELL: Sheet = set(Keyword.CELL);
    export const CROSSHAIR: Sheet = set(Keyword.CROSSHAIR);
    export const TEXT: Sheet = set(Keyword.TEXT);
    export const VERTICAL_TEXT: Sheet = set(Keyword.VERTICAL_TEXT);
    export const ALIAS: Sheet = set(Keyword.ALIAS);
    export const COPY: Sheet = set(Keyword.COPY);
    export const MOVE: Sheet = set(Keyword.MOVE);
    export const NO_DROP: Sheet = set(Keyword.NO_DROP);
    export const NOT_ALLOWED: Sheet = set(Keyword.NOT_ALLOWED);
    export const GRAB: Sheet = set(Keyword.GRAB);
    export const GRABBING: Sheet = set(Keyword.GRABBING);
    export const ALL_SCROLL: Sheet = set(Keyword.ALL_SCROLL);
    export const COL_RESIZE: Sheet = set(Keyword.COL_RESIZE);
    export const ROW_RESIZE: Sheet = set(Keyword.ROW_RESIZE);
    export const N_RESIZE: Sheet = set(Keyword.N_RESIZE);
    export const E_RESIZE: Sheet = set(Keyword.E_RESIZE);
    export const S_RESIZE: Sheet = set(Keyword.S_RESIZE);
    export const W_RESIZE: Sheet = set(Keyword.W_RESIZE);
    export const NE_RESIZE: Sheet = set(Keyword.NE_RESIZE);
    export const NW_RESIZE: Sheet = set(Keyword.NW_RESIZE);
    export const SE_RESIZE: Sheet = set(Keyword.SE_RESIZE);
    export const SW_RESIZE: Sheet = set(Keyword.SW_RESIZE);
    export const EW_RESIZE: Sheet = set(Keyword.EW_RESIZE);
    export const NS_RESIZE: Sheet = set(Keyword.NS_RESIZE);
    export const NESW_RESIZE: Sheet = set(Keyword.NESW_RESIZE);
    export const NWSE_RESIZE: Sheet = set(Keyword.NWSE_RESIZE);
    export const ZOOM_IN: Sheet = set(Keyword.ZOOM_IN);
    export const ZOOM_OUT: Sheet = set(Keyword.ZOOM_OUT);
}
